name: ci-cd

on:
  push
  
jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      working-directory: backend
      run: |
        pip install --quiet fastapi
        pip install --quiet uvicorn
        pip install --quiet flake8
        pip install --quiet pylint
    - name: Lint code
      working-directory: backend
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0114 --disable=C0116 --disable=W0612 --disable=R0912 --disable=R0914 --disable=W0603 --disable=C0103 --disable=R0915 --disable=R0913 *.py
        
  test-frontend:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 17
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
        dir: 'frontend'
    - name: Test the app
      uses: borales/actions-yarn@v4
      with:
        cmd: lint
        dir: 'frontend'
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build
        dir: 'frontend'
  
#   build-frontend:
#     needs: test-frontend 
#     runs-on: ubuntu-22.04
#     steps:
#       - uses: actions/checkout@v3
#       - name: Log into Heroku
#         run: HEROKU_API_KEY='7f8ccb1b-5a0f-48b3-89c1-843df01c40ec' heroku container:push web -a prisoners-dilemma
#       - name: Build docker image
#         working-directory: frontend
#         run: docker build . --file Dockerfile --tag ghcr.io/pawelos991/frontend:${{ github.run_id }}
#       - name: Log into GitHub Container Registry
#         run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
#       - name: Push image to GitHub Container Registry
#         run: |
#           IMAGE_ID=ghcr.io/pawelos991/frontend:${{ github.run_id }}
#           docker push $IMAGE_ID
    
  build-backend:
    needs: test-backend 
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        working-directory: backend
        run: heroku container:push web -a prisoners-dilemma-backend
  
  deploy-backend:
    needs: build-backend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy backend image
        run: heroku container:release web -a prisoners-dilemma-backend
        
        
    
