name: ci-cd

on:
  push
  
jobs:
  test-backend:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install requirements
      working-directory: backend
      run: |
        pip install --quiet fastapi
        pip install --quiet uvicorn
        pip install --quiet flake8
        pip install --quiet pylint
    - name: Lint code
      working-directory: backend
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0114 --disable=C0116 --disable=W0612 --disable=R0912 --disable=R0914 --disable=W0603 --disable=C0103 --disable=R0915 --disable=R0913 *.py
        
  test-frontend:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Setup Yarn
      uses: mskelton/setup-yarn@v1
    - name: Lint frontend
      working-directory: frontend
      run: |
        yarn install
        yarn lint
